# syntax=docker/dockerfile:1
FROM centos:7
 
RUN yum update -y && \
    yum install -y wget initscripts && \
    yum install -y cronie && \
    yum clean all && \
    sed -i -r '/session\s+required\s+pam_loginuid.so/d' /etc/pam.d/crond
 
# TO get components (i.e. --id=...) to install, run the following command: ./CyberProtect_AgentForLinux_x86_64.bin --components-list
# Install only --id="BackupAndRecoveryAgent" component:
RUN --mount=source=AcronisBackupSetup,target=/tmp/acronis_setup \
    /tmp/acronis_setup -a --skip-prereq-check --skip-registration --id="BackupAndRecoveryAgent"
 
COPY rsrc_agent/start.sh /opt/start.sh
COPY rsrc_agent/register_mms.sh /register_mms.sh

CMD ["/bin/bash", "/opt/start.sh"]